### ISSUE TITLE
Port nerdstein/password_policy_zxcvbn

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/password_strength#1]
Refactor the module into password strength port.

https://github.com/nerdstein/password_policy_zxcvbn

**Comment by nerdstein** [comment]
Please make sure the plugin ID / name is refactored to "Password Strength" as well.

**Comment by nerdstein** [comment]
Need to pull down code found in https://github.com/d8-contrib-modules/password_policy not d.o (I havent updated yet).

**Comment by lahoosascoots** [comment]
I think we can call this closed. It's "ported" into this repo. I just don't know if it work's due to an issue in password policy.
