### ISSUE TITLE
Remove plugin managers, do straight port of library

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/password_strength#2]
-Keep settings form
-Load library through Composer, refactor module logic to call this plugin directly instead of 
     -Remove plugin managers 
     -Remove custom implementation of zxcvbn-php library found within the module
     -Composer.json file -> https://packagist.org/packages/bjeavons/zxcvbn-php

**Comment by nerdstein** [comment]
@mjl3475 - would be worth considering as part of issue #1

**Comment by nerdstein** [comment]
This would make substantially less to "bring over"

**Comment by lahoosascoots** [comment]
Sweet. Ctools is throwing a fatal.

Fatal error: Class 'Drupal\system\Controller\FormAjaxController' not found in /Users/matthew.lucasiewicz/src/beta_d8/modules/ctools/src/Controller/WizardAjaxController.php on line 21

**Comment by lahoosascoots** [comment]
So I've converted a few matchers to still be plugins, but to use the libraries code.

I'm not so sure we should remove the Plugin manager entirely as I don't think we want to remove the ability for users to create their own strength plugins.

**Comment by nerdstein** [comment]
Let's discuss this. I had to get buy-in from the module maintainer. They thought it was a strong proponent for "out of the box usability" of the module

**Comment by nerdstein** [comment]
Current plugin systems: scorers, matchers, and searchers.

We see value in keeping the "Matcher" plugin system, and removing searchers and scorers. Matchers will handle other use cases that can influence a password strength score for specific use cases.

Two remaining issues to get to this point:
1. Remove scorers and searchers (this should be done in the context if this ticket)
2. Create a new service that wraps default matchers and matchers pulled from plugins (new ticket)

**Comment by lahoosascoots** [comment]
Scorer and Searcher plugin managers removed in https://github.com/d8-contrib-modules/password_strength/commit/9da81df6ba0af791274f8ab45452f90ad8e8e8f5

**Comment by lahoosascoots** [comment]
Closing.
