### ISSUE TITLE
Create a new Service that wraps default matchers and matchers pulled from plugins

### ISSUE THREAD

**Issue by nerdstein** [d8-contrib-modules/password_strength#4]
1. Create new Service for retrieving matchers
2. Automatically register matchers from library without having to annotate with Drupal classes
3. Automatically register matchers from plugin manager
4. Abstract all matcher operations into Services

**Comment by nerdstein** [comment]
This may not need to be a service, could just wrap a Controller class around it

**Comment by nerdstein** [comment]
CC: @CashWilliams

**Comment by nerdstein** [comment]
Class autoloading consideration: http://symfony.com/doc/current/components/class_loader/psr4_class_loader.html

**Comment by lahoosascoots** [comment]
PR #10

**Comment by lahoosascoots** [comment]
Merged
