### ISSUE TITLE
Consider module dependency on composer_module

### ISSUE THREAD

**Issue by CashWilliams** [d8-contrib-modules/password_strength#5]
Installing this works fine until try to change a password. Then you get a fatal error because composer has never run to bring in the Zxcvbn library.

If we make this dependent on composer_module, at least a site builder will walk through the steps of installing it and see that composer needs to be updated post install.

**Comment by nerdstein** [comment]
Assigned

**Comment by lahoosascoots** [comment]
PR #10

**Comment by lahoosascoots** [comment]
Merged
